
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import Container from "@mui/material/Container";
import Header from "@/components/Header";
import {AppRouterCacheProvider} from '@mui/material-nextjs/v13-appRouter'
import { ThemeProvider } from '@mui/material/styles';
import theme from '../theme'
import "./globals.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <AppRouterCacheProvider options={{ key: 'css' }}>
            <ThemeProvider theme={theme}>
              <Header />
              {children}
            </ThemeProvider>
          </AppRouterCacheProvider>
        </body>        
      </html>
    </ClerkProvider>
  );
}

// Notes:

// APPROUTERCACHEPROVIDER:
// The AppRouterCacheProvider component is responsible for collecting
// the CSS generated by MUI System on the server, 
// as Next.js is streaming chunks of the .html page to the client.
// This component is responsible for making sure that the client side
// MUI custom theme is passed to the server

// CLERKPROVIDER
// This component is required to get information from Clerk Authentication